export const data = [
    {
        id: 1,
        title: 'France Arrests Rwandan Millionaire Accused of Financing 1994 Genocide - The New York Times',
        image_url: 'https://static01.nyt.com/images/2020/05/17/world/17rwanda/16rwanda01-facebookJumbo.jpg',
        intro: 'PARIS One of the most-wanted fugitives of the 1994 Rwanda genocide, accused of financing the slaughter of as many as one million people, mostly Tutsis, was arrested in a Paris suburb early on Saturday, the French police said, ending a decades-long internation… [+5464 chars]',
        source: 'Nytimes.com',
        date: '30 May 2020',
        url: 'https://www.nytimes.com/2020/05/16/world/europe/france-rwanda-genocide-kabuga.html',
    },
    {
        id: 2,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 3,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 4,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        
        id: 5,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 6,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 7,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 8,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 9,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 10,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 11,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 12,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 13,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        
        id: 14,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 16,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 17,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 18,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        
        id: 19,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        
        id: 20,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 21,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        
        id: 22,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        
        id: 23,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'The citizen',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
    {
        id: 24,
        title: 'Title 1',
        image_url: 'https://picsum.photos/700',
        intro: 'Introduction of news',
        source: 'Millard Ayo',
        date: '30 May 2020',
        url: 'https://millardayo.com/video-hitimisho-la-mafunzo-ya-porini-ya-kijeshi-ya-jwtz-kwa-askari-3052/',
    },
];